### ISSUE TITLE
Add OpenID-Connect logic

### ISSUE THREAD

**Issue by shakedmanes** [meateam/OSpike#4]
### Todo:

- [ ] Add OIDC Authorization Code flow
- [ ] Add OIDC Implicit flow
- [ ] Add OIDC Hybrid flow
- [ ] Add JWT ID Token model with validation and generation

**Comment by shakedmanes** [comment]
Resolved in #90.
